# Generated by Django 5.1.6 on 2025-03-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
