# Generated by Django 5.1.6 on 2025-03-30 20:41

import professores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0002_professor_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to=professores.models.nome_arquivo_foto_perfil),
        ),
    ]
